import { StyleSheet, Dimensions } from "react-native";

const width = Dimensions.get('window').width

const styles = StyleSheet.create({
    tabView:{
        backgroundColor: '#fff',
        textAlign: 'center',
        justifyContent: 'center',
    },
    rowCenter: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'center',
        textAlign: 'center',
    },
    row: {
        flexDirection: 'row',
        width: '100%',
    },
    rowSpace: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-between',
    },
    center: {
        alignItems: 'center',
        textAlign: 'center',
        marginTop: 15,
        marginBottom: 15,
    },
    loginTitle: {
        fontSize: 18,
        color: '#303030',
        fontWeight: 'bold',
        marginBottom: 30,
        marginTop: 15,
    },
    loginBold: {
        fontSize: 18,
        color: '#303030',
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 10,
    },
    loginInformation: {
        fontSize: 14,
        width: '80%',
        color: '#606060',
        textAlign: 'center',
        marginBottom: 30,
        marginTop: 30,
    },
    loginOuterLabel: {
        fontSize: 14,
        color: '#606060',
        textAlign: 'center',
    },
    loginLabel: {
        width: '90%',
        marginHorizontal: 10,
        marginTop: 10,
        paddingLeft: 15,
        marginBottom: -40,
    },
    loginInput: {
        width: '90%',
        backgroundColor: 'white',
        height: 55,
        margin: 12,
    },
    loginPassword: {
        width: '90%',
        margin: 12,
    },
    textfatura: {
        fontSize: 14,
        color: '#606060',
        marginTop: 10,
        marginBottom: 10,
    },
    textfaturaRightBold: {
        fontSize: 14,
        color: '#606060',
        alignSelf: 'flex-end',
        fontWeight: 'bold',
        marginTop: 10,
        marginBottom: 10,
    },
    buttonSubmit: {
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        backgroundColor: '#00a5e4',
        paddingTop: 14,
        paddingBottom: 14,
        marginLeft: 12,
        marginTop: 30,
    },
    textButtonSubmit: {
        fontSize: 20,
        color: '#fff',
    },
    buttonSubmitDisabled: {
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        backgroundColor: '#aeaeae',
        paddingTop: 14,
        paddingBottom: 14,
        marginLeft: 12,
        marginTop: 30,
    },
    buttonOutline: {
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        borderColor: '#00a5e4',
        borderWidth: 2,
        borderStyle: 'solid',
        paddingTop: 14,
        paddingBottom: 14,
        marginLeft: 12,
        marginTop: 30,
    },
    textButtonOutline: {
        fontSize: 20,
        color: '#00a5e4',
    },
    buttonFornecimento:{
        position: 'absolute',
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '25%',
        backgroundColor: '#00a5e4',
        paddingTop: 8,
        paddingBottom: 8,
        top: 18,
        right: 10,
        zIndex: 9999,
    },
    textButtonFornecimento: {
        fontSize: 14,
        color: '#fff',
    },
    buttonPagar:{
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '50%',
        backgroundColor: '#00a5e4',
        paddingTop: 8,
        paddingBottom: 8,
    },
    checkBoxContainer: {
        alignItems: 'center',
        textAlign: 'center',
        marginTop: 30,
        flexDirection: "row",
        justifyContent: 'center',
    },
    checkBoxLabel: {
        fontSize: 14,
        color: '#606060',
        alignSelf:'center',
        textAlign:'center',
        marginLeft: 10,
    },
    hyperlink: {
        fontSize: 14,
        color: '#00a5e4',
        textDecorationLine: "underline",
        marginBottom: 10,
        marginTop: 20,
    },
    linkContainer: {
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
    faturasContainer: {
        backgroundColor: '#1e3650',
        color: '#fff',
        width: width,
        height: 500,
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
    },
    faturasValor: {
        fontSize: 40,
        color: '#fff',
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 10,
    },
    faturasTextBold: {
        fontSize: 14,
        color: '#fff',
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 10,
    },
    faturasText: {
        fontSize: 14,
        color: '#fff',
        marginBottom: 20,
        marginTop: 10,
    },
    cardContainer: {
        flexDirection: "row",
        width: width,
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardFatura: {
        backgroundColor: '#fff',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        color: '#606060',
        width: '70%',
        height: '100%',
        alignSelf: 'center'
    },
    cardText: {
        fontSize: 14,
        color: '#303030', 
        marginBottom: 20,
        marginTop: 10,
    },
    cardVencido: {
        fontSize: 16,
        fontWeight: "bold",
        color: 'red',
        marginBottom: 10,
        marginTop: 10,
    },
    cardOk: {
        fontSize: 16,
        fontWeight: "bold",
        color: 'green',
        marginBottom: 10,
        marginTop: 10,
        textAlign: 'center'
    },
    cardValor: {
        fontSize: 32,
        fontWeight: "bold",
    },
    downloadIcon: {
        color: '#000',
        margin: 10,
    },
    buttonCardBar: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'center',
        marginBottom: 10,
    },
    buttonCard: {
        width: 60,
        height: 60,
        borderWidth: 0.5,
        borderColor: '#d0d0d0',
        borderRadius: 5,
        margin: 20,
        marginTop: 5,
        alignItems: 'center'
    },
    buttonCardIcon: {
        alignSelf: 'center',
        marginTop: 17,
    },
    buttonCardText: {
        fontSize: 8,
    },
    itemNumber: {
        marginTop: 10,
        marginRight: 20,
        color: '#00a5e4',
        fontWeight: 'bold',
    },
    image: {
        width: '100%',
        height: 160,
        alignItems: 'center',
        justifyContent: 'center',
    },
    rightMenu: {
        flexDirection: 'row',
        alignContent: 'space-between',
        position: 'absolute',
        right: 15,
        top: 0,
        color: 'white'
    },
    leftMenu: {
        marginLeft: 15,
    },
    modalView: {
        margin: 15,
        backgroundColor: "white",
        borderRadius: 20,
        padding: 15,
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 2
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5
    },
    modalTitle: {
        textAlign: 'center',
        fontSize: 14,
        marginBottom: 10,
        color: '#00a5e4',
        fontWeight: 'bold',
    },
    modalText: {
        textAlign: 'center',
        fontSize: 14,
    },
    modalImagem: {
        borderRadius: 20,
        width: '100%',
        marginTop: 15,
        marginBottom: 15,
    },
    modalButton: {
        alignSelf: 'flex-end',
        marginBottom: 10,
        marginRight: 15,
    },
    modalButtonText: {
        color: '#00a5e4',
        fontWeight: 'bold',
        fontSize: 16,
    },
});

export default styles;