import { StyleSheet, Dimensions } from "react-native";

const width = Dimensions.get('window').width

const styles = StyleSheet.create({
    tabView:{
        backgroundColor: '#fff',
        textAlign: 'center',
        justifyContent: 'center',
    },
    rowCenter: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'center',
        textAlign: 'center',
    },
    row: {
        flexDirection: 'row',
        width: '100%',
    },
    rowSpace: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-between',
    },
    center: {
        alignItems: 'center',
        textAlign: 'center',
        paddingHorizontal: 15
    },
    titlePagamento: {
        fontSize: 18,
        color: '#FFFFFF',
        fontWeight: 'bold',
        marginTop: 30,
        marginBottom: 70,
    },
    loginTitle: {
        fontSize: 18,
        color: '#303030',
        fontWeight: 'bold',
        marginBottom: 30,
        marginTop: 30,
    },
    loginBold: {
        fontSize: 18,
        color: '#303030',
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 10,
    },
    loginInformation: {
        fontSize: 14,
        color: '#606060',
        textAlign: 'center',
        marginBottom: 30,
    },
    loginOuterLabel: {
        fontSize: 14,
        color: '#606060',
        textAlign: 'center',
    },
    loginLabel: {
        width: '90%',
        marginHorizontal: 10,
        marginTop: 10,
        paddingLeft: 15,
        marginBottom: -40,
    },
    loginInput: {
        width: '90%',
        margin: 12,
    },
    loginPassword: {
        width: '90%',
        margin: 12,
    },
    faturaSelecionadaTitle: {
        fontSize: 18,
        color: '#303030',
        fontWeight: 'bold',
        marginBottom: 30,
        marginTop: 90,
        alignSelf: 'center',
    },
    textfatura: {
        fontSize: 14,
        color: '#606060',
        marginTop: 10,
        marginBottom: 10,
    },
    textfaturaRightBold: {
        fontSize: 14,
        color: '#606060',
        alignSelf: 'flex-end',
        fontWeight: 'bold',
        marginTop: 10,
        marginBottom: 10,
    },
    buttonBanco: {
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        backgroundColor: '#1e3650',
        paddingTop: 14,
        paddingBottom: 14,
        marginLeft: 12,
        marginTop: 30,
        marginBottom: 20,
    },
    textButtonBanco: {
        fontSize: 20,
        color: '#fff',
    },
    buttonOutline: {
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        borderColor: '#00a5e4',
        borderWidth: 2,
        borderStyle: 'solid',
        paddingTop: 14,
        paddingBottom: 14,
        marginLeft: 12,
        marginTop: 30,
    },
    textButtonOutline: {
        fontSize: 20,
        color: '#00a5e4',
    },
    buttonFornecimento:{
        position: 'absolute',
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '25%',
        backgroundColor: '#00a5e4',
        paddingTop: 8,
        paddingBottom: 8,
        top: 18,
        right: 10,
        zIndex: 9999,
    },
    textButtonFornecimento: {
        fontSize: 14,
        color: '#fff',
    },
    buttonPagar:{
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '50%',
        backgroundColor: '#00a5e4',
        paddingTop: 8,
        paddingBottom: 8,
    },
    checkBoxContainer: {
        alignItems: 'center',
        textAlign: 'center',
        paddingHorizontal: 15,
        flexDirection: "row",
        justifyContent: 'center',
    },
    checkBoxLabel: {
        fontSize: 14,
        color: '#606060',
        alignSelf:'center',
        textAlign:'center',
        marginLeft: 10,
    },
    hyperlink: {
        fontSize: 14,
        color: 'blue',
        alignSelf:'center',
        textAlign:'center',
        textDecorationLine: "underline",
        marginBottom: 10,
        marginTop: 10,
    },
    linkContainer: {
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
    faturasContainer: {
        backgroundColor: '#1e3650',
        color: '#fff',
        width: width,
        height: 600,
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
    },
    faturasValor: {
        fontSize: 40,
        color: '#fff',
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 10,
    },
    faturasTextBold: {
        fontSize: 14,
        color: '#fff',
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 10,
    },
    faturasText: {
        fontSize: 14,
        color: '#fff',
        marginBottom: 20,
        marginTop: 10,
    },
    cardContainer: {
        flexDirection: "row",
        width: width,
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardContainerPagamento: {
        position: 'absolute',
        bottom: -70,
        flexDirection: "row",
        width: width,
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardFatura: {
        backgroundColor: '#fff',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        color: '#606060',
        width: '70%',
        height: '100%',
        alignSelf: 'center'
    },
    cardPagamento: {
        backgroundColor: '#fff',
        padding: 10,
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        color: '#606060',
        width: '80%',
        overflow: 'visible',
        height: '100%',
        alignSelf: 'center'
    },
    cardText: {
        fontSize: 14,
        color: '#303030', 
        marginBottom: 20,
        marginTop: 10,
    },
    cardVencido: {
        fontSize: 16,
        fontWeight: "bold",
        color: 'red',
        marginBottom: 10,
        marginTop: 10,
    },
    cardOk: {
        fontSize: 16,
        fontWeight: "bold",
        color: 'green',
        marginBottom: 10,
        marginTop: 10,
    },
    cardValor: {
        fontSize: 32,
        fontWeight: "bold",
    },
    cardPagamentoText: {
        fontSize: 14,
        color: '#303030', 
        fontWeight: 'bold',
        marginBottom: 20,
        marginTop: 10,
    },
    downloadIcon: {
        color: '#000',
        margin: 10,
    },
    codigoDeBarras: {
        fontSize: 20,
        alignSelf: 'center',
        fontWeight: 'bold',
        paddingTop: 30,
        paddingBottom: 30,
    },
    buttonCardBar: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'center',
        marginBottom: 10,
    },
    buttonCard: {
        width: 60,
        height: 60,
        borderWidth: 0.5,
        borderColor: '#d0d0d0',
        borderRadius: 5,
        margin: 20,
        marginTop: 5,
        alignItems: 'center'
    },
    buttonCardIcon: {
        alignSelf: 'center',
        marginTop: 17,
    },
    buttonCardText: {
        fontSize: 8,
    },
    itemNumber: {
        marginTop: 10,
        marginRight: 20,
        color: '#00a5e4',
        fontWeight: 'bold',
    },
    bancoLogo: {
        width: 100,
        height: 100,
        marginTop: 10,
    },
    centerTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
});

export default styles;