import { StyleSheet, Dimensions } from "react-native";

const width = Dimensions.get('window').width

const styles = StyleSheet.create({
    tabView:{
        backgroundColor: '#fff',
        textAlign: 'center',
        justifyContent: 'center',
    },
    row: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'center',
        textAlign: 'center',
    },
    center: {
        alignItems: 'center',
        textAlign: 'center',
        paddingHorizontal: 15
    },
    loginTitle: {
        fontSize: 18,
        color: '#303030',
        fontWeight: 'bold',
        marginBottom: 30,
        marginTop: 30,
    },
    loginBold: {
        fontSize: 18,
        color: '#303030',
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 10,
    },
    loginInformation: {
        fontSize: 14,
        color: '#606060',
        textAlign: 'center',
        marginBottom: 30,
    },
    loginOuterLabel: {
        fontSize: 14,
        color: '#606060',
        textAlign: 'center',
    },
    loginLabel: {
        width: '90%',
        marginHorizontal: 10,
        marginTop: 10,
        paddingLeft: 15,
        marginBottom: -40,
    },
    loginInput: {
        width: '90%',
        margin: 12,
    },
    loginPassword: {
        width: '90%',
        margin: 12,
    },
    buttonSubmit: {
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        backgroundColor: '#00a5e4',
        paddingTop: 14,
        paddingBottom: 14,
        marginLeft: 12,
        marginTop: 30,
    },
    textButtonSubmit: {
        fontSize: 20,
        color: '#fff',
    },
    buttonOutline: {
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        borderColor: '#00a5e4',
        borderWidth: 2,
        borderStyle: 'solid',
        paddingTop: 14,
        paddingBottom: 14,
        marginLeft: 12,
        marginTop: 30,
    },
    textButtonOutline: {
        fontSize: 20,
        color: '#00a5e4',
    },
    buttonFornecimento:{
        position: 'absolute',
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '25%',
        backgroundColor: '#00a5e4',
        paddingTop: 8,
        paddingBottom: 8,
        top: 18,
        right: 10,
        zIndex: 9999,
    },
    textButtonFornecimento: {
        fontSize: 14,
        color: '#fff',
    },
    buttonPagar:{
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        width: '50%',
        backgroundColor: '#00a5e4',
        paddingTop: 8,
        paddingBottom: 8,
    },
    checkBoxContainer: {
        alignItems: 'center',
        textAlign: 'center',
        paddingHorizontal: 15,
        flexDirection: "row",
        justifyContent: 'center',
    },
    checkBoxLabel: {
        fontSize: 14,
        color: '#606060',
        alignSelf:'center',
        textAlign:'center',
        marginLeft: 10,
    },
    hyperlink: {
        fontSize: 14,
        color: 'blue',
        alignSelf:'center',
        textAlign:'center',
        textDecorationLine: "underline",
        marginBottom: 10,
        marginTop: 10,
    },
    linkContainer: {
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
    faturasContainer: {
        backgroundColor: '#1e3650',
        color: '#fff',
        width: width,
        height: '60%',
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
    },
    faturasValor: {
        fontSize: 40,
        color: '#fff',
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 10,
    },
    faturasTextBold: {
        fontSize: 14,
        color: '#fff',
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 10,
    },
    faturasText: {
        fontSize: 14,
        color: '#fff',
        //fontWeight: 'bold',
        marginBottom: 20,
        marginTop: 10,
    },
    cardContainer: {
        flexDirection: "row",
        width: width,
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardFatura: {
        backgroundColor: '#fff',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        color: '#606060',
        width: '70%',
        height: '100%',
        alignSelf: 'center'
    },
    cardText: {
        fontSize: 14,
        color: '#303030', 
        marginBottom: 20,
        marginTop: 10,
    },
    cardVencido: {
        fontSize: 16,
        fontWeight: "bold",
        color: 'red',
        marginBottom: 10,
        marginTop: 10,
    },
    cardOk: {
        fontSize: 16,
        fontWeight: "bold",
        color: 'green',
        marginBottom: 10,
        marginTop: 10,
    },
    cardValor: {
        fontSize: 32,
        fontWeight: "bold",
    },
    downloadIcon: {
        color: '#000',
        margin: 10,
    },
});

export default styles;