import { StyleSheet } from "react-native";
import Constants from 'expo-constants';
import Collapsible from "react-native-collapsible";

const styles = StyleSheet.create({
  container: {
    width: '100%',
    marginBottom: 30,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  steps: {
    flexDirection: 'row',
    alignContent: 'space-between',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  activeStep: {
    paddingHorizontal: 5,
    color: '#303030',
  },
  inactiveStep: {
    paddingHorizontal: 5,
    color: '#e0e0e0',
  },
  parcelaTexto: {
    fontSize: 14,
    color: '#303030',
    textAlign: 'center',
    marginBottom: 30,
    marginRight: 12,
    marginLeft: 12,
    justifyContent: 'center',
    width: '90%',
  },
  parcelaTextoLeft: {
    fontSize: 14,
    color: '#303030',
    marginBottom: 15,
    marginRight: 12,
    marginLeft: 12,
  },
  parcelaTextoRight: {
    position: 'absolute',
    fontSize: 14,
    color: '#303030',
    right: 12,
    marginBottom: 15,
    marginRight: 12,
    marginLeft: 12,
  },
  parcelaTextoSmallLeft: {
    fontSize: 10,
    color: '#303030',
    marginBottom: 15,
    marginRight: 12,
    marginLeft: 12,
  },
  parcelaTextoSmallRight: {
    position: 'absolute',
    fontSize: 10,
    color: '#303030',
    right: 12,
    marginBottom: 15,
    marginRight: 12,
    marginLeft: 12,
  },
  parcelaTextoBold: {
    fontSize: 14,
    color: '#303030',
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 30,
    marginBottom: 20,
  },
  parcelaTextoBoldLeft: {
    fontSize: 14,
    color: '#303030',
    fontWeight: 'bold',
    marginBottom: 15,
    marginRight: 12,
    marginLeft: 12,
  },
  parcelaTextoBoldRight: {
    position: 'absolute',
    right: 12,
    fontSize: 14,
    color: '#303030',
    fontWeight: 'bold',
    marginBottom: 15,
    marginRight: 12,
    marginLeft: 12,
  },
  parcelaTexto50: {
    fontSize: 14,
    color: '#303030',
    marginBottom: 15,
    marginRight: 12,
    marginLeft: 12,
    width: '50%',
    alignSelf: 'flex-start',
  },
  parcelaTextoGray: {
    color: '#b0b0b0',
    fontSize: 16,
    paddingTop: 30,
    marginBottom: 20,
    alignSelf: 'center',
  },
  buttonSubmit: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    backgroundColor: '#00a5e4',
    paddingTop: 14,
    paddingBottom: 14,
    marginLeft: 12,
    marginTop: 30,
  },
  textButtonSubmit: {
    fontSize: 20,
    color: '#fff',
  },
  buttonSubmitDisabled: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    backgroundColor: '#aeaeae',
    paddingTop: 14,
    paddingBottom: 14,
    marginLeft: 12,
    marginTop: 30,
  },
  buttonOutline: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    borderColor: '#00a5e4',
    borderWidth: 2,
    borderStyle: 'solid',
    paddingTop: 14,
    paddingBottom: 14,
    marginLeft: 12,
    marginTop: 30,
  },
  textButtonOutline: {
    fontSize: 20,
    color: '#00a5e4',
  }, 
  comboBox: {
    borderRadius: 5,
    borderColor: '#f0f0f0',
    borderWidth: 2,
    borderStyle: 'solid',
    height: 65,
    margin: 12,
    marginBottom: 30,
    paddingTop: 20,
    paddingLeft: 15,
    overflow: 'hidden',
  },
  halfView: {
    width: '45%'
  },
  switchContainer: {
    width: '95%',
    marginLeft: 15,
    marginRight: 15,
    flexDirection: 'row',
  },
  switch: {
    marginRight: 15,
  },
  link: {
    fontSize: 14,
    color: 'blue',
    alignSelf:'center',
    textAlign:'center',
    textDecorationLine: "underline",
  },
  linkContainer: {
    alignItems: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  select: {
    width: '90%',
    marginLeft: 12,
  },
  collapsibleHeader: {
    flexDirection: 'row',
    alignContent: 'space-between',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  collapsibleHeaderText: {
    marginLeft: 12,
    fontSize: 18,
    alignSelf: 'flex-start',
  },
  collapsible: {},
  caret: {
    alignSelf: 'flex-end',
    marginRight: 10,
    marginLeft: 5,
  },
  collapsibleFooter: {
    flexDirection: 'row',
    alignContent: 'space-between',
    justifyContent: 'space-between',
    marginLeft: 12,
    marginRight: 12,
    marginBottom: 25,
  },
  collapsibleFooterText: {
    fontWeight: 'bold',
    fontSize: 18,
    alignSelf: 'center',
    width: '61%'
  },
  hyperlink: {
    fontSize: 14,
    color: 'blue',
    textDecorationLine: "underline",
    marginBottom: 10,
    marginTop: 10,
  },
});

export default styles;